### PR TITLE
STYLEGUIDE: raise maximum characters.

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
This rule is very loosely conformed to and 100 seems fairly arbitrary. Instead, let's loosen it slightly and provide a justification for that loosening.

CC @cheshire137 who pointed this out to me in https://github.com/github/github/pull/160489#discussion_r513778065.

As an unrelated comment: it would be lovely if we could (one day) punt rules like this to RuboCop itself and have it populate all existing TODOs/exceptions. This is exactly the type of rule best done by machines rather than humans 🤖 👩🏻‍🎨

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Picking a few random people from contributors: @joelhawksley @rmosolgo @tma @skalnik @BlakeWilliams @cheshire137: any thoughts?

**Review by BlakeWilliams — APPROVED** [review]
I think I generally prefer fewer characters, but 118 doesn't seem like that much more and the reasoning behind it makes a ton of sense. 👍

**Comment by MikeMcQuaid** [comment]
Thanks @BlakeWilliams, @joelhawksley!

**Comment by use931** [comment]
Yse

-

**Pull request merged**
