### PR TITLE
Namespace Changes for RuboCop 0.70

### PR DESCRIPTION
**Pull request by joshRpowell**
Drops support for Ruby < 2.3

### CODE REVIEW

**Comment by joaoffcosta** [comment]
@joshRpowell I believe this is no longer a WIP as the title suggests. I'm using your branch and it seems to be working great 👍

**Comment by MrChrisW** [comment]
Thanks for this @joshRpowell 👍 I think we may want to add https://github.com/rubocop-hq/rubocop-performance as a dependency since https://github.com/rubocop-hq/rubocop/issues/5977 ?

```
Warning: unrecognized cop Performance/CaseWhenSplat found in config/default.yml
Warning: unrecognized cop Performance/Count found in config/default.yml
Warning: unrecognized cop Performance/Detect found in config/default.yml
Warning: unrecognized cop Performance/DoubleStartEndWith found in config/default.yml
Warning: unrecognized cop Performance/EndWith found in config/default.yml
Warning: unrecognized cop Performance/FlatMap found in config/default.yml
Warning: unrecognized cop Performance/RangeInclude found in config/default.yml
Warning: unrecognized cop Performance/RedundantMatch found in config/default.yml
Warning: unrecognized cop Performance/RedundantMerge found in config/default.yml
Warning: unrecognized cop Performance/ReverseEach found in config/default.yml
Warning: unrecognized cop Performance/Size found in config/default.yml
```

**Comment by joshRpowell** [comment]
@MrChrisW great catch!  had added in app, but didn't circle back.  removed in app after adding the dependency here and all is green.

**Comment by MrChrisW** [comment]
@joshRpowell no problem! thanks again for tackling this 🎊 

fyi @jhawthorn as you seem active here 😊 looks like we'll need to cut a new release once this is merged

**Pull request merged**
