### PR TITLE
Migrate accessibility rubocop rule `ImageHasAlt` from dotcom to erblint-github

### PR DESCRIPTION
**Pull request by bolonio**
## Context

The motivation of [rubocop-github](https://github.com/github/rubocop-github) is to open-source our accessibility rubocop rules so non-GitHub people can benefit from them, have a space to provide comprehensive rule documentation, and also allow rules to be shared between Rails projects.

This PR migrates the accessibility rule `ImageHasAlt` from dotcom to [rubocop-github](https://github.com/github/rubocop-github)

### Related Issue

- https://github.com/github/accessibility/issues/1430

### CODE REVIEW

**Review by owenniblock — APPROVED** [review]

**Comment by khiga8** [comment]
We should also update one of the config files. Maybe [config/default.yml](https://github.com/github/rubocop-github/blob/master/config/default.yml)?

Or do you think it should be in an accessibiliy-specific one?

**Review by khiga8 — CHANGES_REQUESTED** [review]
Could we create a new `accessibility` folder to house the accessibility rules?

This will ensure the file path reflects the module structure.

```
module RuboCop
  module Cop
    module GitHub
      module Accessibility
```

Then the file names shouldn't include `rails_`

**Review by owenniblock — APPROVED** [review]
Looks good to me!

**Review by khiga8 — APPROVED** [review]
Awesomeeee

**Pull request merged**
